name: Generate SEO files
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create robots.txt
        run: |
          echo "User-agent: *" > robots.txt
          echo "Allow: /" >> robots.txt
          echo "Disallow: /admin/" >> robots.txt
          echo "" >> robots.txt
          echo "Sitemap: https://polinafort.github.io/sitemap.xml" >> robots.txt
      - name: Create sitemap.xml
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          echo '  <url>' >> sitemap.xml
          echo '    <loc>https://polinafort.github.io/</loc>' >> sitemap.xml
          echo '    <lastmod>2024-01-15</lastmod>' >> sitemap.xml
          echo '    <changefreq>weekly</changefreq>' >> sitemap.xml
          echo '    <priority>1.0</priority>' >> sitemap.xml
          echo '  </url>' >> sitemap.xml
          echo '  <url>' >> sitemap.xml
          echo '    <loc>https://polinafort.github.io/anti-stress.html</loc>' >> sitemap.xml
          echo '    <lastmod>2024-01-15</lastmod>' >> sitemap.xml
          echo '    <changefreq>weekly</changefreq>' >> sitemap.xml
          echo '    <priority>0.8</priority>' >> sitemap.xml
          echo '  </url>' >> sitemap.xml
          echo '  <url>' >> sitemap.xml
          echo '    <loc>https://polinafort.github.io/romantic.html</loc>' >> sitemap.xml
          echo '    <lastmod>2024-01-15</lastmod>' >> sitemap.xml
          echo '    <changefreq>weekly</changefreq>' >> sitemap.xml
          echo '    <priority>0.8</priority>' >> sitemap.xml
          echo '  </url>' >> sitemap.xml
          echo '  <url>' >> sitemap.xml
          echo '    <loc>https://polinafort.github.io/horror.html</loc>' >> sitemap.xml
          echo '    <lastmod>2024-01-15</lastmod>' >> sitemap.xml
          echo '    <changefreq>weekly</changefreq>' >> sitemap.xml
          echo '    <priority>0.8</priority>' >> sitemap.xml
          echo '  </url>' >> sitemap.xml
          echo '</urlset>' >> sitemap.xml
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
